on:
  push:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  emobon_job:
    runs-on: ubuntu-latest
    name: emobon dm gdrive downloader job
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: download
        uses: emo-bon/emobon_dm_gdrive_downloader@master
      - name: rocrate-to-sembench
        uses: vliz-be-opsci/rocrate-to-sembench@main
        env:
          PROFILE: https://raw.githubusercontent.com/emo-bon/emo-bon-profile-0.1/main
      - name: clean
        run: sudo rm -rf ~sembench_data_cache ~sembench_arguments.json
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
