on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  job0:
    runs-on: ubuntu-latest
    name: emobon rocrate workflow
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: download
        uses: emo-bon/emobon_dm_gdrive_downloader@master
      - name: rocrate-to-sembench
        uses: vliz-be-opsci/rocrate-to-sembench@main
        env:
          PROFILE: https://raw.githubusercontent.com/emo-bon/emo-bon-profile-0.1/main
      - name: semantify
        uses: vliz-be-opsci/semantify@main
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
